name: Production Deploy

on:
  push:
    branches: ["main"]

env:
  SECRET: ${{ secrets.SECRET }}

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: checking user
        run: whoami

      - name: checking npm
        run: npm -v

      - name: Install dependencies on the machine
        run: npm ci

      - name: Restart PM2 trial
        run: pm2 restart example-api -a
